api:
  replicaCount: 2
  image:
    repository: ghcr.io/gaboracnicolai/edge-osb
    tag: "e51e304cf2cf4bff91a180a650f029ce80ff2ed1"  # pin to the SHA you pushed
    pullPolicy: IfNotPresent
  port: 8080
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 256Mi

worker:
  replicaCount: 2
  image:
    repository: ghcr.io/gaboracnicolai/edge-osb
    tag: "e51e304cf2cf4bff91a180a650f029ce80ff2ed1"  # pin to the SHA you pushed
    pullPolicy: IfNotPresent
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 256Mi

config:
  existingSecret: edge-osb-secrets

serviceAccount:
  create: true
  name: ""

podAnnotations:
  prometheus.io/scrape: "true"
  prometheus.io/port: "8080"

nameOverride: ""
fullnameOverride: ""
