apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: auth-service
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: edge-infra
  source:
    repoURL: https://github.com/gaboracnicolai/edge-infra
    targetRevision: HEAD
    path: deploy/helm/auth-service
    helm:
      valueFiles:
        - values.yaml
        - ../../../envs/prod/eu-west-1/values-auth-service.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: infra
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - RespectIgnoreDifferences=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        maxDuration: 3m
        factor: 2
  ignoreDifferences:
    - group: ""
      kind: Secret
      jsonPointers:
        - /data
  revisionHistoryLimit: 10
