apiVersion: v1
kind: Service
metadata:
  name: {{ include "edge-ratelimit.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "edge-ratelimit.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "edge-ratelimit.selectorLabels" . | nindent 4 }}
  ports:
    - name: grpc
      port: {{ .Values.service.grpcPort }}
      targetPort: grpc
      protocol: TCP
