apiVersion: v1
kind: Service
metadata:
  name: {{ include "edge-secrets.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "edge-secrets.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "edge-secrets.selectorLabels" . | nindent 4 }}
  ports:
    - name: mtls
      port: {{ .Values.service.port }}
      targetPort: mtls
      protocol: TCP
