apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "edge-controller.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "edge-controller.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "edge-controller.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "edge-controller.selectorLabels" . | nindent 8 }}
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      serviceAccountName: {{ include "edge-controller.serviceAccountName" . }}
      containers:
        - name: controller
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: metrics
              containerPort: 8080
              protocol: TCP
          env:
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POSTGRES_DSN
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.postgres.existingSecret }}
                  key: {{ .Values.postgres.secretKey }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
