apiVersion: v1
kind: Service
metadata:
  name: {{ include "edge-controller.fullname" . }}-metrics
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "edge-controller.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    {{- include "edge-controller.selectorLabels" . | nindent 4 }}
  ports:
    - name: metrics
      port: 8080
      targetPort: metrics
      protocol: TCP
