apiVersion: v1
kind: Service
metadata:
  name: {{ include "edge-osb.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "edge-osb.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    {{- include "edge-osb.apiSelectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.api.port }}
      targetPort: http
      protocol: TCP
