apiVersion: v1
kind: Service
metadata:
  name: {{ include "edge-control-plane.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "edge-control-plane.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "edge-control-plane.selectorLabels" . | nindent 4 }}
  ports:
    - name: grpc
      port: {{ .Values.service.grpcPort }}
      targetPort: grpc
      protocol: TCP
    - name: metrics
      port: {{ .Values.service.metricsPort }}
      targetPort: metrics
      protocol: TCP
