replicaCount: 1

image:
  repository: ghcr.io/gaboracnicolai/edge-controller
  tag: "447ceb18980fc02fdc7e28db16354c62e3018850"  # pin to the SHA you pushed
  pullPolicy: IfNotPresent

postgres:
  existingSecret: edge-control-plane-postgres
  secretKey: dsn

serviceAccount:
  create: true
  name: edge-controller

leaderElection:
  namespace: infra

resources:
  requests:
    cpu: 100m
    memory: 64Mi
  limits:
    cpu: 500m
    memory: 256Mi

podAnnotations: {}

nameOverride: ""
fullnameOverride: ""
