replicaCount: 1

image:
  repository: ghcr.io/gaboracnicolai/edge-controller
  tag: "e51e304cf2cf4bff91a180a650f029ce80ff2ed1"  # pin to the SHA you pushed
  pullPolicy: IfNotPresent

postgres:
  existingSecret: edge-control-plane-postgres
  secretKey: dsn

serviceAccount:
  create: true
  name: edge-controller

leaderElection:
  namespace: infra

resources:
  requests:
    cpu: 100m
    memory: 64Mi
  limits:
    cpu: 500m
    memory: 256Mi

podAnnotations: {}

nameOverride: ""
fullnameOverride: ""
